### ISSUE TITLE
upgrade httpclient5.1 to the latest version and adjust the manifest OSGi properties

### ISSUE THREAD

**Issue by jcompagner** [eclipse/ecf#11] opened 2022-10-11 08:16 UTC
Not sure who does this, but i think ECF is the one that provides the http client of apache to the eclipse platform (and we also need that so we reuse it)
Problem is that the current shipping one has a bug (that we can work around) so it would be nice to upgrade httpclient5 to 5.1.4

But the bigger problem is that i think eclipse (orbit??) adjusts the http client jars so that it is a real OSGi package (is there already a case reported to https://issues.apache.org/jira/projects/HTTPCORE/issues/HTTPCORE-484?filter=allopenissues (and/or maybe also the client project) to fix this really in there stuff? So that the mvn central deployed jar is directly usable?

The problem is that eclipse/orbit now generates its own set of OSGi properties including the import package.. which is:
org.slf4j;version="[1.7. 25,2)"
 
so excluding org.slf4j2 which is annoying because that is where now also Log4J moved to 

We can't use 1.7 because 1.7 has this:

Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.5))"

and in an OSGi environment to have that whole logging over all plugins and rerouted to Log4J we need:

Require-Capability: osgi.extender;filter:="(osgi.extender=osgi.servicelo
 ader.processor)",osgi.serviceloader;filter:="(osgi.serviceloader=org.sl
 f4j.spi.SLF4JServiceProvider)"

so enable the service loader stuff..

That was always in slf4j 1.8 But that version was always kind of in beta and is now fully replaced by 2.0

and now it is tricky because in our eclipse plugin we can't really say we use slf4j2;2.0 and also depend on the httpclient..
then i think osgi reports that as a conflict 

besides that, still 2 slf4j are getting up because both of them are shipped:

Oct 11, 2022 10:13:42 AM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider org.apache.logging.log4j.jcl.LogFactoryImpl of service org.apache.commons.logging.LogFactory in bundle org.apache.logging.log4j.jcl
Oct 11, 2022 10:13:42 AM org.apache.aries.spifly.BaseActivator log
INFO: Registered provider org.apache.logging.slf4j.SLF4JServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle org.apache.logging.log4j.slf4j2-impl
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

and we get that at startup. so the SLF4J 2.0 is working but the last 3 lines i guess are because of SLF4J 1.7 not working.

**Comment by jcompagner** [comment] 2022-10-11 09:02
hmm i need to have 1 plugin that needs to do both, so import slf4j and httpclient, and that is then a problem:

org.osgi.framework.BundleException: Could not resolve module: com.servoy.eclipse.extension.compatibility [21]
  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource com.servoy.eclipse.extension.compatibility [osgi.identity; osgi.identity="com.servoy.eclipse.extension.compatibility"; type="osgi.bundle"; version:Version="2022.12.0.3820_rc"; singleton:="true"] because it is exposed to package 'org.slf4j' from resources slf4j.api [osgi.identity; osgi.identity="slf4j.api"; type="osgi.bundle"; version:Version="2.0.3"] and org.slf4j.api [osgi.identity; osgi.identity="org.slf4j.api"; type="osgi.bundle"; version:Version="1.7.30.v20200204-2150"] via two dependency chains.

Chain 1:
  com.servoy.eclipse.extension.compatibility [osgi.identity; osgi.identity="com.servoy.eclipse.extension.compatibility"; type="osgi.bundle"; version:Version="2022.12.0.3820_rc"; singleton:="true"]
    import: (&(osgi.wiring.package=org.slf4j)(version>=2.0.3))
     |
    export: osgi.wiring.package: org.slf4j
  slf4j.api [osgi.identity; osgi.identity="slf4j.api"; type="osgi.bundle"; version:Version="2.0.3"]

Chain 2:
  com.servoy.eclipse.extension.compatibility [osgi.identity; osgi.identity="com.servoy.eclipse.extension.compatibility"; type="osgi.bundle"; version:Version="2022.12.0.3820_rc"; singleton:="true"]
    require: (osgi.wiring.bundle=org.apache.httpcomponents.client5.httpclient5)
     |
    provide: osgi.wiring.bundle; bundle-version:Version="5.1.2.v20211217-1500"; osgi.wiring.bundle="org.apache.httpcomponents.client5.httpclient5"
  org.apache.httpcomponents.client5.httpclient5 [osgi.identity; osgi.identity="org.apache.httpcomponents.client5.httpclient5"; type="osgi.bundle"; version:Version="5.1.2.v20211217-1500"]
    import: (&(osgi.wiring.package=org.slf4j)(&(version>=1.7.25)(!(version>=2.0.0))))
     |
    export: osgi.wiring.package: org.slf4j
  org.slf4j.api [osgi.identity; osgi.identity="org.slf4j.api"; type="osgi.bundle"; version:Version="1.7.30.v20200204-2150"]

so i guess for now we need to keep using the 1.8 version of SLF4J

**Comment by scottslewis** [comment] 2022-10-12 02:21
> Not sure who does this, but i think ECF is the one that provides the http client of apache to the eclipse platform (and we also need that so we reuse it) Problem is that the current shipping one has a bug (that we can work around) so it would be nice to upgrade httpclient5 to 5.1.4
> 

Ok.  I generally maintain ECF...although some of that is also done by platform committer Aleksandar Kurtakov

Here's the basics

Our github repo is here:   https://github.com/eclipse/ecf

Here is the feature that we currently contribute to the platform for p2 filetransfer: 

https://github.com/eclipse/ecf/tree/master/releng/features/org.eclipse.ecf.filetransfer.httpclient5.feature

As you can see from the feature.xml here

https://github.com/eclipse/ecf/blob/master/releng/features/org.eclipse.ecf.filetransfer.httpclient5.feature/feature.xml

// This one is the ECF provider based upon Apache httpclient5
         id="org.eclipse.ecf.provider.filetransfer.httpclient5"
// This is org.apache.commons.codec...required by httpclient5
         id="org.apache.commons.codec"
// commons logging, also required by httpclient5
         id="org.apache.commons.logging"
// the apache httpcomponents client5
         id="org.apache.httpcomponents.client5.httpclient5"
// the apache httpcomponents client5 windows support (proxy)
         id="org.apache.httpcomponents.client5.httpclient5-win"
// apache httpcomponents httpcore
         id="org.apache.httpcomponents.core5.httpcore5"
// httpcomponents httpcore5-h2
         id="org.apache.httpcomponents.core5.httpcore5-h2"

So you are right...we don't provide the implementation of the org.apache.httpcomponents. or the org.apache.commons.* bundles.

These bundles (the apache ones) are provided by the target platform, which for ECF's builder (used to produce the p2 repo provided to platform) is defined here

https://github.com/eclipse/ecf/tree/master/releng/org.eclipse.ecf.releng.target

specifically/currently using this target file:

https://github.com/eclipse/ecf/blob/master/releng/org.eclipse.ecf.releng.target/ecf-2022-03.target

Here are the relevant versions currently in this target (and so currently deployed with platform):

			<unit id="org.apache.commons.codec" version="1.14.0.v20200818-1422"/>
			<unit id="org.apache.commons.logging" version="1.2.0.v20180409-1502"/>
	
		<unit id="org.apache.httpcomponents.client5.httpclient5" version="5.1.2.v20211217-1500"/>
			<unit id="org.apache.httpcomponents.client5.httpclient5-win" version="5.1.2.v20211217-1500"/>
			<unit id="org.apache.httpcomponents.core5.httpcore5" version="5.1.2.v20211217-1500"/>
			<unit id="org.apache.httpcomponents.core5.httpcore5-h2" version="5.1.2.v20211217-1500"/>


All of these builds of httpcomponents jars is done by the *Orbit project...i.e. here is the repository URL defined in our target file above):

https://download.eclipse.org/tools/orbit/downloads/drops/R20220302172233/repository

Here are all the Orbit repos:

https://download.eclipse.org/tools/orbit/downloads/

There is a more recent Orbit repo:

https://download.eclipse.org/tools/orbit/downloads/drops/R20220830213456/

But the version here of httpclient5 appears to be:  5.1.2.v20220426-0826...e.g.

https://download.eclipse.org/tools/orbit/downloads/drops/R20220830213456/repository/plugins/org.apache.httpcomponents.client5.httpclient5_5.1.2.v20220426-0826.jar

So, if what you need is 5.1.4 then the *first* thing is to get the Orbit maintainer for the httpclient5 impl to support 5.1.4 (seems to be Matthias Sohn).   We are not the only consumers of the Orbit httpclient5 impl, but our is contributed to Eclipse and so it's usually the preferred one.

I guess what I'm saying is:   It's easy for use to update our target platform to a new version of httpclient5 (e.g. 5.1.4), but only if it's already in Orbit.....i.e. we (and the platform) consume the httpclient5 jars as bundles from Orbit/Matthias by simply updating our target file (to new repo) rebuilding the ECF httpclient5 feature into new p2 repo, testing, and then making the repo available to the platform.

> But the bigger problem is that i think eclipse (orbit??) adjusts the http client jars so that it is a real OSGi package (is there already a case reported to https://issues.apache.org/jira/projects/HTTPCORE/issues/HTTPCORE-484?filter=allopenissues (and/or maybe also the client project) to fix this really in there stuff? So that the mvn central deployed jar is directly usable?

Yes, that's done by the Orbit project maintainer for httpclient5 (Matthias Sohn).

> 
> The problem is that eclipse/orbit now generates its own set of OSGi properties including the import package.. which is: org.slf4j;version="[1.7. 25,2)"
> 
> so excluding org.slf4j2 which is annoying because that is where now also Log4J moved to
> 
> We can't use 1.7 because 1.7 has this:
> 
> Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.5))"
> 
> and in an OSGi environment to have that whole logging over all plugins and rerouted to Log4J we need:
> 
> Require-Capability: osgi.extender;filter:="(osgi.extender=osgi.servicelo ader.processor)",osgi.serviceloader;filter:="(osgi.serviceloader=org.sl f4j.spi.SLF4JServiceProvider)"
> 
> so enable the service loader stuff..
> 
> That was always in slf4j 1.8 But that version was always kind of in beta and is now fully replaced by 2.0
> 
> and now it is tricky because in our eclipse plugin we can't really say we use slf4j2;2.0 and also depend on the httpclient.. then i think osgi reports that as a conflict
> 
> besides that, still 2 slf4j are getting up because both of them are shipped:
> 
> Oct 11, 2022 10:13:42 AM org.apache.aries.spifly.BaseActivator log INFO: Registered provider org.apache.logging.log4j.jcl.LogFactoryImpl of service org.apache.commons.logging.LogFactory in bundle org.apache.logging.log4j.jcl Oct 11, 2022 10:13:42 AM org.apache.aries.spifly.BaseActivator log INFO: Registered provider org.apache.logging.slf4j.SLF4JServiceProvider of service org.slf4j.spi.SLF4JServiceProvider in bundle org.apache.logging.log4j.slf4j2-impl SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". SLF4J: Defaulting to no-operation (NOP) logger implementation SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> 
> and we get that at startup. so the SLF4J 2.0 is working but the last 3 lines i guess are because of SLF4J 1.7 not working.

I think this is all for discussion with httpclient5 maintainers (Matthias and/or other Orbit committers).  They are in control of all the org.apache.* bundles meta-data (manifest) and dependencies/versions etc.   

Does that make sense?

**Comment by jcompagner** [comment] 2022-10-12 08:49
I also created yesterday a case at Orbit and they alraedy patched it: https://git.eclipse.org/r/c/orbit/orbit-recipes/+/196310

this https://ci.eclipse.org/orbit/job/gerrit-orbit-recipes/1941/artifact/releng/repository-all/target/repository/plugins/ now generates the right stuff.

so it would be nice if ECF will be using the latest http components (so also updating the minor version to 5.1.4 and 5.1.3) that do have now the slf4j range from [1.7 to 3) (so including 2)

**Comment by scottslewis** [comment] 2022-10-12 23:25
From https://download.eclipse.org/tools/orbit/downloads/ 
it looks as though Orbit project releases integration builds every Friday, so the next one would be on 10/14/22.   After that's available I will update the ECF target to use this new repo and do another ECF build , test and provide to the platform hopefully next week.

One question:   Will we/ECF have to include any other bundles (e.g. slf4j of some version) to provide to the platform in our p2 repo?   Please let me know if so.

**Comment by jcompagner** [comment] 2022-10-13 07:13
http components do depend on SLF4J but there is already a case for that on platform:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/588

(to update fully to 2, that would be a problem with the current http component libs that ECF now uses)

**Comment by HannesWell** [comment] 2022-10-13 21:36
> so it would be nice if ECF will be using the latest http components (so also updating the minor version to 5.1.4 and 5.1.3) that do have now the slf4j range from [1.7 to 3) (so including 2)

I have not checked the version ranges that are required/imported by ecf, but as long as the upper bound is not too restrictive it should not be necessary to lift the lower bound (unless you use part of the the API of newer versions).
It is mainly a matter of what is available in the SimRel repos and as long as anybody provides/contributes a newer version that still fits in the range, that version is included in the SimRel repo.
And since Eclipse Platform has httpclient in its TP and we are willing to adapt newer versions quickly (if they work), Eclipse-Platform can be the project that effectively contributes it.

**Comment by jonahgraham** [comment] 2022-11-02 15:07
> it looks as though Orbit project releases integration builds every Friday

Orbit releases I-builds for every commit made to Orbit, plus it releases Stable builds for each SimRel milestone/release candidate. The [latest one of those](https://download.eclipse.org/tools/orbit/downloads/drops/S20221018231518/repository/plugins/) has the updated bundles and the next S-build will be made on Nov 8th.

**Comment by scottslewis** [comment] 2022-11-05 21:41
I've updated the ECF target platform to use the Orbit bundles in stable build 

https://download.eclipse.org/tools/orbit/downloads/drops/S20221018231518/repository/plugins/

I've adjusted the version ranges for ECF package imports with lower bound of [5.1.3/4 and upper bound of 6)

then built a p2 repo here

https://download.eclipse.org/rt/ecf/3.14.34/site.p2/3.14.34.v20221105-0315/

I've run the ECF filetransfer junit test suite on this build and all of these tests are passing.

I've test installed everything into Eclipse 9-2022 and run successfully with p2.   Other than manifest import version range changes and bundle version bumps, there were not any ECF filetransfer changes.

I would ask that people on this issue install into their environment and verify that 5.1.3/4 updates have fixed the dependency issues that prompted this issue (and not caused any detectable regressions) in your network and OS environment.  Thanksindvance for that.

Without objection from anyone on this issue or elsewhere, my plan is to contribute this build to platform on Monday, Nov 7 ~noon ET by posting comment to https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/591 with link to p2 repo above.

**Comment by scottslewis** [comment] 2022-11-08 00:10
I've contributed ECF 3.14.34 to platform via eclipse-platform/eclipse.platform.releng.aggregator#591.

Closing this issue.   Please do testing on next platform integration build after platform releng updates ECF contribution to 3.14.34.

**Closed by scottslewis** 2022-11-08 00:10 UTC
