### ISSUE TITLE
Setup on the contribution page fails

### ISSUE THREAD

**Issue by opcoach** [eclipse/ecf#135] opened 2024-11-29 09:47 UTC
I used the setup configuration on this page : https://github.com/eclipse/ecf/blob/master/CONTRIBUTING.md

Drag and drop in the installer and I got this error during install : 

![image](https://github.com/user-attachments/assets/bb74507e-9a9c-4c86-b261-57b925757c91)

**Comment by scottslewis** [comment] 2024-11-29 21:02
I need @merks to help with diagnosis on this, as he's the author of the .setup file referenced.

**Comment by merks** [comment] 2024-11-30 08:05
The problem is here:

https://github.com/eclipse/ecf/blob/e355fb411958bd12f0c678e5a76476198c8048e8/releng/features/org.eclipse.ecf.xmpp.feature/feature.xml#L48

which was introduced by this commit.

https://github.com/eclipse/ecf/commit/70d98df687a3c61b2e602bacae0774789069532d#diff-fdc3f9d6ab8d3c5235a7bd75c45771e2cfd477cdeef1ed95c318ba8786b800e4R58

I'm not sure which problem that fixed, but now whenever the Orbit version is upgraded, the setup will be broken.  Also, you will no longer be following the latest Orbit versions and will generally cause problems contributing to SimRel, e.g., causing duplicates like this one:

![image](https://github.com/user-attachments/assets/5776dca0-1338-4d78-8d6a-00e3c6768540)

Of course it would be best **to not include 3rd party libraries in features.**

Changing it back to 0.0.0 fixed the problem and generates a new target platform

![image](https://github.com/user-attachments/assets/81797dc9-018b-41aa-a1e4-9d4116773779)

But there is still a sea of red because JDT no longer support BREE < 1.8.

![image](https://github.com/user-attachments/assets/87f6e7c4-d6df-4139-b8df-3904bd975cc2)

How best can I help address these types of issues?  It's very tedious work to upgrade all the projects:

![image](https://github.com/user-attachments/assets/64d9ab2d-40c0-4282-a9f7-6c0e16c89625)

PDE now has a Modify button to make the upgrade easier, i.e., the settings and the classpath need to change too.

So I can help do this, but given it's a lot of work, so I want to be sure that a PR will be processed before investing that effort.

**Comment by scottslewis** [comment] 2024-11-30 18:12
> The problem is here:
> 
> https://github.com/eclipse/ecf/blob/e355fb411958bd12f0c678e5a76476198c8048e8/releng/features/org.eclipse.ecf.xmpp.feature/feature.xml#L48
> 
> which was introduced by this commit.
> 
> [70d98df#diff-fdc3f9d6ab8d3c5235a7bd75c45771e2cfd477cdeef1ed95c318ba8786b800e4R58](https://github.com/eclipse/ecf/commit/70d98df687a3c61b2e602bacae0774789069532d#diff-fdc3f9d6ab8d3c5235a7bd75c45771e2cfd477cdeef1ed95c318ba8786b800e4R58)

Thanks.

> 
> I'm not sure which problem that fixed, but now whenever the Orbit version is upgraded, the setup will be broken. Also, you will no longer be following the latest Orbit versions and will generally cause problems contributing to SimRel, e.g., causing duplicates like this one:
> 

<stuff deleted>

> 
> Of course it would be best **to not include 3rd party libraries in features.**

Yes.   As I recall, this is an old feature who's 3rd party library (formerly from Orbit) had a version increment.

> 
> Changing it back to 0.0.0 fixed the problem and generates a new target platform
> 

<stuff deleted>

> 
> But there is still a sea of red because JDT no longer support BREE < 1.8.
> 

<stuff deleted>

> 
> How best can I help address these types of issues? It's very tedious work to upgrade all the projects:
> 

Yes.

<stuff deleted>

> 
> PDE now has a Modify button to make the upgrade easier, i.e., the settings and the classpath need to change too.
> 
> So I can help do this, but given it's a lot of work, so I want to be sure that a PR will be processed before investing that effort.

At the moment I'm not able to process prs...so no, please do not invest the effort.    I appreciate the offer Ed.

If/when I can, I may do some removal of older features and bundles from ECF build, so that may help things.  But that's not going to be immediate.

@opcoach :  Sorry, I'm afraid this setup may not work for a while.

**Comment by scottslewis** [comment] 2024-12-08 23:31
I've modified the .target file used in the build in the following way:  I've removed the reference to the problematic library (org.xbill.dns) in the orbit-aggregation repo, and replaced it with use of a (new) maven central location/repo that has the required version (3.6.2)  See ecf-2024-06.target file diff in this commit:

https://github.com/eclipse/ecf/commit/8e0e523f033efc357e2e1c1649aec81fb6ae50d5

After feature version updates, this builds fine...as org.xbill.dns 3.6.2 exists (under new name dnsjava) at maven central, but does not seem to exist (with either old or new name) in orbit-aggregation.

Here's the successful snapshot build job:  https://ci.eclipse.org/ecf/job/ecf-github.master/129/

And the snapshot repo resulting from that build:   https://download.eclipse.org/rt/ecf/snapshot/

I intend to use this target (ecf-2024-06.target file) for at least the next release of ECF...and hopefully beyond that.

I'm not sure whether or exactly what needs to change in the .setup file for this new target to work with oomph...I'm hoping it takes nothing at all.    And it will now just work for initial workspace configuration via oomph.  

I'm closing this for now, please reopen if there are additional changes for this to work with the updated .target file.

**Closed by scottslewis** 2024-12-08 23:31 UTC
